services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: agrosmart-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
